#!/usr/bin/env bash
# Configure an Ubuntu server so localhost resolves to 127.0.0.2
# and facebook.com resolves to 8.8.8.8
file=~/hosts.new
cp /etc/hosts $file

echo "127.0.0.2		localhost" > $file
echo "8.8.8.8		facebook.com" >> $file

cp -f $file /etc/hosts
